[tool.poetry]
name = "python-gcp-api"
version = "0.1.0"
description = ""
authors = ["GIORGIO PULCINI <giorgio.pulcini@alice.it>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
